"""add_oauth_fields_to_users

Revision ID: 4f2833283c9d
Revises: a9538e885478
Create Date: 2025-09-17 22:01:38.160804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2833283c9d'
down_revision = 'a9538e885478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('oaut_provider', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.drop_column('users', 'oaut_provider')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###
