"""add_email_code_and_reset_token_columns

Revision ID: a7bea8c51de5
Revises: d0f9a5984f7a
Create Date: 2025-09-10 22:54:35.078914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bea8c51de5'
down_revision = 'd0f9a5984f7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('email_code', sa.String(length=6), nullable=True, comment='6-digit code for email verification'))
    op.add_column('email_verifications', sa.Column('reset_token', sa.String(length=128), nullable=True, comment='32+ char secure token for password reset'))
    op.drop_column('email_verifications', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('email_verifications', 'reset_token')
    op.drop_column('email_verifications', 'email_code')
    # ### end Alembic commands ###
