"""drop_email_unique_constraint

Revision ID: a9538e885478
Revises: a7bea8c51de5
Create Date: 2025-09-10 23:21:06.701382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9538e885478'
down_revision = 'a7bea8c51de5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_verifications_email_key'), 'email_verifications', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('email_verifications_email_key'), 'email_verifications', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
