"""fix typo in oaut_provider

Revision ID: e890315c1e77
Revises: 4f2833283c9d
Create Date: 2025-10-12 21:24:23.704545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e890315c1e77'
down_revision = '4f2833283c9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'oaut_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oaut_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
